# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - master-source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: ::set-env name=DEV_TOKEN::${{ secrets.GH_TOKEN }} && ::set-env name=GA_ID::${{ secrets.GA_ID }}
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: master
