# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - master-source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GA_ID: ${{ secrets.GA_ID }}
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: master
