name: build
on:
  push:
    branches-ignore:
      - master
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: Lint
        run: yarn run lint

      - name: Lint
        run: yarn run clean

      - name: Build
        run: yarn run build
        env:
            GA_ID: ${{ secrets.GA_ID }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
            GOODREADS_SECRET_KEY: ${{ secrets.GOODREADS_SECRET_KEY }}
            SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
            SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Test
        run: yarn run test

      - name: Build and Deploy to Github Pages
        if: github.ref == 'refs/heads/production-source'
        uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GA_ID: ${{ secrets.GA_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          GOODREADS_SECRET_KEY: ${{ secrets.GOODREADS_SECRET_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: production
