# This is a basic workflow to help you get started with Actions
name: build

on:
  push:
    branches:
      - master-source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GA_ID: ${{ secrets.GA_ID }}
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          GOODREADS_SECRET_KEY: ${{ secrets.GOODREADS_SECRET_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        with:
          access-token: ${{ secrets.GH_TOKEN }}
          deploy-branch: master
